import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {rank,normalizePreferences,pricePerMl,hasExcludedNote,compareOffers,explainConcentration} from '../dist/engine.js';
const catalog=JSON.parse(fs.readFileSync('dist/catalog.json'));
test('normalizes country and currency',()=>{assert.equal(normalizePreferences({country:'CA'}).currency,'CAD');assert.equal(normalizePreferences({country:'XX'}).country,'US')});
test('deduplicates normalized choices',()=>assert.deepEqual(normalizePreferences({liked_notes:[' Vanilla ','vanilla','']}).liked_notes,['vanilla']));
test('validates budget',()=>{assert.equal(normalizePreferences({budget:-1}).budget,Infinity);assert.equal(normalizePreferences({budget:'175'}).budget,175)});
test('calculates exact unit price',()=>assert.equal(pricePerMl({price:150,size_ml:100}),1.5));
test('rejects malformed offers',()=>{for(const o of [{price:-1,size_ml:10},{price:2,size_ml:0},{price:NaN,size_ml:10}])assert.throws(()=>pricePerMl(o))});
test('hard-excludes exact disliked notes',()=>{const r=rank(catalog,{country:'US',disliked_notes:['vanilla']});assert.ok(!r.some(x=>x.notes.includes('vanilla')))});
test('does not substring-exclude different notes',()=>{const p=catalog.products.find(x=>x.id==='light-blue-edt');assert.equal(hasExcludedNote(p,['lemon']),false)});
test('never crosses country offers',()=>{for(const x of rank(catalog,{country:'CA'}))assert.ok(x.offers.every(o=>o.country==='CA'))});
test('Canada uses native CAD only',()=>{for(const x of rank(catalog,{country:'CA'}))assert.ok(x.offers.every(o=>o.currency==='CAD'))});
test('US has seven comparable products',()=>assert.equal(rank(catalog,{country:'US'}).length,7));
test('Canada honestly has two products',()=>assert.equal(rank(catalog,{country:'CA'}).length,2));
test('Libre wins lavender warm floral request',()=>assert.equal(rank(catalog,{country:'US',families:['warm floral'],liked_notes:['lavender'],intensity:'bold'})[0].id,'libre-edp'));
test('Black Opium wins coffee gourmand evening request',()=>assert.equal(rank(catalog,{country:'US',families:['gourmand'],liked_notes:['coffee'],occasions:['evening'],intensity:'bold'})[0].id,'black-opium-edp'));
test('Light Blue wins citrus lemon daytime request',()=>assert.equal(rank(catalog,{country:'US',families:['citrus'],liked_notes:['sicilian lemon'],occasions:['daytime'],intensity:'soft'})[0].id,'light-blue-edt'));
test('Pear Inc wins pear fresh office request',()=>assert.equal(rank(catalog,{country:'US',families:['fresh fruity'],liked_notes:['green pear'],occasions:['office'],intensity:'medium'})[0].id,'pear-inc-edp'));
test('Daisy wins soft fruity floral office request',()=>assert.equal(rank(catalog,{country:'US',families:['fruity floral'],liked_notes:['wild berries'],occasions:['office'],intensity:'soft'})[0].id,'daisy-edt'));
test('budget affects explanation and affordability',()=>{const r=rank(catalog,{country:'US',budget:30});assert.ok(r.every(x=>!x.affordable));assert.ok(r.every(x=>x.score<=90))});
test('offer sorting prefers full-size value',()=>{const p=rank(catalog,{country:'US'}).find(x=>x.id==='light-blue-edt');assert.equal(p.best_offer.size_ml,100);assert.equal(compareOffers(p.offers)[0].size_ml,100)});
test('stable ranking regardless catalog order',()=>{const p={country:'US',families:['fruity floral']};assert.deepEqual(rank(catalog,p).map(x=>x.id),rank({...catalog,products:[...catalog.products].reverse(),offers:[...catalog.offers].reverse()},p).map(x=>x.id))});
test('scores remain bounded and explained',()=>{for(const p of [{},{families:['gourmand'],liked_notes:['vanilla'],intensity:'bold',country:'US'},{country:'CA',budget:100}])for(const r of rank(catalog,p)){assert.ok(r.score>=0&&r.score<=100);assert.ok(r.reasons.length)}});
test('concentration education avoids guarantees',()=>{for(const c of ['Eau de Toilette','Eau de Parfum','Eau de Parfum Intense'])assert.match(explainConcentration(c),/not|varies|guarantee/i)});
