import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {JSDOM} from 'jsdom';import {init} from '../dist/app.js';
const html=fs.readFileSync('dist/index.html','utf8'),catalog=JSON.parse(fs.readFileSync('dist/catalog.json'));
function env(){const d=new JSDOM(html,{url:'https://example.test/'});return {d,doc:d.window.document,fetcher:async()=>({ok:true,json:async()=>catalog})}}
test('loads US catalog and cards',async()=>{const e=env();await init(e.doc,e.fetcher,e.d.window.localStorage);assert.equal(e.doc.querySelectorAll('.card').length,7);assert.match(e.doc.querySelector('#resultTitle').textContent,/United States/)});
test('country switches currency and coverage',async()=>{const e=env();await init(e.doc,e.fetcher,e.d.window.localStorage);const ca=e.doc.querySelector('[name=country][value=CA]');ca.checked=true;ca.dispatchEvent(new e.d.window.Event('change'));assert.equal(e.doc.querySelector('#currencyLabel').textContent,'CAD');assert.equal(e.doc.querySelectorAll('.card').length,2)});
test('disliked-note select removes products',async()=>{const e=env();await init(e.doc,e.fetcher,e.d.window.localStorage);e.doc.querySelector('#disliked').value='vanilla';e.doc.querySelector('#preferences').dispatchEvent(new e.d.window.Event('submit',{cancelable:true}));assert.ok([...e.doc.querySelectorAll('.card .notes')].every(x=>!x.textContent.includes('vanilla')))});
test('shortlist saves, opens and removes',async()=>{const e=env();await init(e.doc,e.fetcher,e.d.window.localStorage);e.doc.querySelector('[data-save]').click();assert.equal(e.doc.querySelector('#shortlistCount').textContent,'1');assert.match(e.d.window.localStorage.getItem('scentcompass.shortlist'),/\[/);e.doc.querySelector('#shortlistButton').click();assert.equal(e.doc.querySelector('#shortlist').hidden,false);e.doc.querySelector('[data-remove]').click();assert.equal(e.doc.querySelector('#shortlistCount').textContent,'0')});
test('clear shortlist and scrim close work',async()=>{const e=env();e.d.window.localStorage.setItem('scentcompass.shortlist','["libre-edp"]');await init(e.doc,e.fetcher,e.d.window.localStorage);e.doc.querySelector('#shortlistButton').click();e.doc.querySelector('#clearShortlist').click();assert.equal(e.doc.querySelector('#shortlistCount').textContent,'0');e.doc.querySelector('#scrim').click();assert.equal(e.doc.querySelector('#shortlist').hidden,true)});
test('sort changes order by value',async()=>{const e=env();await init(e.doc,e.fetcher,e.d.window.localStorage);e.doc.querySelector('#sort').value='value';e.doc.querySelector('#sort').dispatchEvent(new e.d.window.Event('change'));const first=e.doc.querySelector('.card').dataset.id;assert.equal(first,'daisy-edt')});
test('network failure is visible',async()=>{const e=env();await init(e.doc,async()=>({ok:false}),e.d.window.localStorage);assert.match(e.doc.querySelector('#status').textContent,/Unable to load/)});
test('malformed local storage recovers',async()=>{const e=env();e.d.window.localStorage.setItem('scentcompass.shortlist','bad');await init(e.doc,e.fetcher,e.d.window.localStorage);assert.equal(e.doc.querySelector('#shortlistCount').textContent,'0')});
test('WebMCP profile tool validates and updates visible state',async()=>{const e=env();let tool;e.doc.modelContext={registerTool:async t=>tool=t};await init(e.doc,e.fetcher,e.d.window.localStorage);assert.equal(tool.name,'set_scent_profile');assert.equal(tool.annotations.readOnlyHint,false);const out=tool.execute({country:'US',families:['citrus'],liked_notes:['sicilian lemon'],disliked_notes:[],occasions:['daytime'],intensity:'soft',budget:200});assert.equal(out.top_ids[0],'light-blue-edt');assert.equal(e.doc.querySelector('.card').dataset.id,'light-blue-edt');assert.equal(e.doc.querySelector('[name=families][value=citrus]').checked,true)});
